from typing import Any

class Decompressor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def process(self, chunk: bytes) -> bytes: ...
    def is_finished(self) -> bool: ...

class Compressor:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def process(self, chunk: bytes) -> bytes: ...
    def finish(self) -> bytes: ...

class error(Exception): ...
